INSERT INTO burgers (burger_name, devoured) VALUES ('The Kitchen Sink Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Western BBQ Bacon Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Double Cheese Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Triple Stack Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Beyond Meat Vegan Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Single With Cheese Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Tillamook Swiss Turkey Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Portobello & Swiss Steakburger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Zesty Ring Stack Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Garlic Aoli & Mushroom Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Haystack Burger', false);
